### ISSUE TITLE
Incompatible with FluentValidation 9.0.0

### ISSUE THREAD

**Issue by mjuen** [MichalJankowskii/FluentValidation.Validators.UnitTestExtension#18]
When updating FluentValidation to Version `9.0.0` the tests with this extension no longer work.

```csharp
Message: 
    System.TypeLoadException : Could not load type 'FluentValidation.Validators.IDelegatingValidator' 
    from assembly 'FluentValidation, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7de548da2fbae0f0'.
  Stack Trace: 
    <>c__DisplayClass0_0`2.<ShouldHaveRules>b__3(IPropertyValidator propertyValidator)
    List`1.ForEach(Action`1 action)
    AbstractValidatorExtension.ShouldHaveRules[T,TProperty](AbstractValidator`1 validator, 
    Expression`1 expression, IValidatorVerifier[] validatorVerifieres)
    AppRegisterDtoValidatorTests.ConcurrencyStamp_ShouldHaveAllValidators() line 19

```

**Comment by Srivatsa6065** [comment]
Same issue

**Comment by MichalJankowskii** [comment]
It looks that with 9.x something changed in engine. I will check it and probably update the library.

**Comment by MichalJankowskii** [comment]
Fixed. It is already on nuget

**Comment by Srivatsa6065** [comment]
Hi Thank you for the fix, The identified issue is working fine, I am little confused writing the test for Child validator

My Validator has rules

  var projectValidator = new InlineValidator<ProjectMessage>();

            projectValidator.RuleFor(project => project.ProjectRno)
                .Must(CheckIfProjectExists)
                .WithMessage(string.Format(CommonMessage.EntityDoesNotExist, CommonMessage.Project));

            RuleForEach(command => command.Projects)
                .SetValidator(projectValidator);

The validator is in a class called AddContactPersonProjectsCommandValidator

The earlier test was write like

new AddContactPersonProjectsCommandValidator().ShouldHaveRules(x => x.Projects,
                BaseVerifiersSetComposer.Build()
                    .AddChildValidatorVerifier<InlineValidator<ProjectMessage>>()
                    .Create());


 This worked fine.

Now with the current update AddChildValidatorVerifier expects TPropery, I am not sure what should be passed into this
I have tried IEnumerable<ProjectMessage>  because x.Projects is  IEnumerable<ProjectMessage> 
I have tried ProjectMessage

Always getting a type mismatch error.

**Comment by MichalJankowskii** [comment]
This change has been introduced due to changes in 9.0:

> ChildValidatorAdaptor and IncludeRule now have generic parameters
> The ChildvalidatorAdaptor and IncludeRule classes now have generic type parameters. This will not affect users of the public API, but may affect anyone using the internal API.

I will double-check because another person have a similar issue.

**Comment by MichalJankowskii** [comment]
I want to let you know that I fixed this issue.
